"""Add Pedido table and modify OrdenTrabajo

Revision ID: 35ced219f453
Revises: d2fc9da55474
Create Date: 2026-05-11 14:59:56.787601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35ced219f453'
down_revision: Union[str, Sequence[str], None] = 'd2fc9da55474'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pedidos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('referencia', sa.String(length=100), nullable=True),
    sa.Column('ruta_carpeta', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('ordenes_trabajo', sa.Column('pedido_id', sa.Integer(), nullable=True))
    op.alter_column('ordenes_trabajo', 'estado',
               existing_type=sa.VARCHAR(length=23),
               nullable=True)
    op.drop_constraint(None, 'ordenes_trabajo', type_='foreignkey')
    op.drop_constraint(None, 'ordenes_trabajo', type_='foreignkey')
    op.drop_constraint(None, 'ordenes_trabajo', type_='foreignkey')
    op.create_foreign_key(None, 'ordenes_trabajo', 'pedidos', ['pedido_id'], ['id'])
    op.drop_column('ordenes_trabajo', 'instalador_id')
    op.drop_column('ordenes_trabajo', 'fecha_actualizacion')
    op.drop_column('ordenes_trabajo', 'creador_id')
    op.drop_column('ordenes_trabajo', 'operador_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordenes_trabajo', sa.Column('operador_id', sa.INTEGER(), nullable=True))
    op.add_column('ordenes_trabajo', sa.Column('creador_id', sa.INTEGER(), nullable=False))
    op.add_column('ordenes_trabajo', sa.Column('fecha_actualizacion', sa.DATETIME(), nullable=True))
    op.add_column('ordenes_trabajo', sa.Column('instalador_id', sa.INTEGER(), nullable=True))
    op.drop_constraint(None, 'ordenes_trabajo', type_='foreignkey')
    op.create_foreign_key(None, 'ordenes_trabajo', 'usuarios', ['instalador_id'], ['id'])
    op.create_foreign_key(None, 'ordenes_trabajo', 'usuarios', ['creador_id'], ['id'])
    op.create_foreign_key(None, 'ordenes_trabajo', 'usuarios', ['operador_id'], ['id'])
    op.alter_column('ordenes_trabajo', 'estado',
               existing_type=sa.VARCHAR(length=23),
               nullable=False)
    op.drop_column('ordenes_trabajo', 'pedido_id')
    op.drop_table('pedidos')
    # ### end Alembic commands ###
