"""Add ruta_muestra y ruta_instalacion a OrdenTrabajo

Revision ID: d2fc9da55474
Revises: 9fdc9b0713f0
Create Date: 2026-05-04 13:24:17.602352

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2fc9da55474'
down_revision: Union[str, Sequence[str], None] = '9fdc9b0713f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ordenes_trabajo', sa.Column('ruta_muestra', sa.String(length=500), nullable=True))
    op.add_column('ordenes_trabajo', sa.Column('ruta_instalacion', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ordenes_trabajo', 'ruta_instalacion')
    op.drop_column('ordenes_trabajo', 'ruta_muestra')
    # ### end Alembic commands ###
